apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: aaa
configMapGenerator:
- envs:
  - .env
  name: aaa-configmap
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
